---
name: Major Version Updater
# Whenever a new release is made, push a major version tag
on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "major=${major}" >> "$GITHUB_OUTPUT"

      - name: force update major tag
        env:
          MAJOR: ${{ steps.version.outputs.major }}
        run: |
          git tag "v${MAJOR}"
          git push origin "refs/tags/v${MAJOR}" -f
